apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: budibase-proxy
  name: proxy-service
spec:
  replicas: {{ .Values.services.proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: budibase-proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: budibase-proxy
    spec:
      {{ if .Values.services.proxy.initContainers }}
      initContainers:
      {{- toYaml .Values.services.proxy.initContainers | nindent 6 }}
      {{ end }}
      containers:
      -
        image: {{ .Values.services.proxy.image }}:{{ .Values.services.proxy.tag | default "k8s" }}
        imagePullPolicy: Always
        name: proxy-service
        ports:
        - containerPort: {{ .Values.services.proxy.port }}
        {{ if .Values.services.proxy.resources }}
        resources:
        {{- toYaml .Values.services.proxy.resources | nindent 10 }}
        {{ end }}
        volumeMounts:
        {{ if .Values.services.proxy.extraVolumeMounts }}
        {{- toYaml .Values.services.proxy.extraVolumeMounts | nindent 8 }}
        {{ end }}
        env:
        {{ if .Values.services.proxy.extraEnvVars }}
        {{- toYaml .Values.services.proxy.extraEnvVars | nindent 8 }}
        {{ end }}
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      {{ if .Values.services.proxy.extraVolumes }}
      {{- toYaml .Values.services.proxy.extraVolumes | nindent 6 }}
      {{ end }}
status: {}
