apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: budibase-proxy
  name: proxy-service
spec:
  replicas: {{ .Values.services.proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: budibase-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: budibase-proxy
    spec:
      {{ if .Values.services.proxy.initContainers }}
      initContainers:
{{ toYaml .Values.services.proxy.initContainers | indent 8 }}
      {{ end }}
      containers:
      - image: budibase/proxy
        imagePullPolicy: ""
        name: proxy-service
        ports:
        - containerPort: {{ .Values.services.proxy.port }}
        resources: {}
        volumeMounts:
          {{ if .Values.services.proxy.volumeMounts }}
{{ toYaml .Values.services.proxy.volumeMounts | indent 10 }}
          {{ end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        {{ if .Values.services.proxy.volumes }}
{{ toYaml .Values.services.proxy.volumes | indent 8 }}
        {{ end }}
status: {}
